openapi: 3.0.0
servers:
  - url: 'http://localhost:9191'
info:
  description: |-
    Crafter Deployer API
  version: '4.5.2'
  title: Crafter Deployer
  termsOfService: ''
  contact:
    email: info@craftercms.org
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
externalDocs:
  description: CrafterCMS - Deployer
  url: 'https://craftercms.com/docs/current/reference/modules/deployer.html'
tags:
  - name: target
    description: Target management  operations
  - name: monitoring
    description: Monitoring operations

paths:

  /api/1/target/create:
    post:
      security: []
      tags:
        - target
      summary: Create a Crafter Deployer target
      description: |
              Module: Deployer <br>
              Target creation is based on templates. The deployer comes with two out of the box: remote and local. The remote template creates targets that pull changes from a remote Git repository, making it ideal to create targets for delivery environments. The local template instead generates targets that use a local Git repo and the last processed commit to infer the changes, without executing a pull, so it’s used mostly to create targets for authoring environments. <br><br> If a target already exists and <b><i>replace</i></b> is true, then the new target will replace the existing one. If <b><i>replace</i></b> is false and the target exists, a 409 is returned.
      operationId: createTarget
      requestBody:
        description: Create target request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTargetRequest'
            examples:
              simpleExample:
                summary: Simple example of the request body
                description: "Module: Deployer"
                value:
                  env: preview
                  site_name: my-editorial
                  replace: true
                  disable_deploy_cron: true
                  template_name: local
                  repo_url: /opt/crafter/data/repos/sites/my-editorial/sandbox
                  engine_url: http://localhost:8080
              withNotificationAddresses:
                summary: Example of request body with notification addresses
                description: "Module: Deployer"
                value:
                  env: dev
                  site_name: my-editorial
                  replace: false
                  template_name: remote
                  repo_url: ssh://crafter@server/opt/crafter/data/repos/sites/my-editorial/published
                  repo_username: crafter
                  repo_password: crafter
                  repo_branch: live
                  engine_url: http://localhost:8080
                  notification_addresses: "admin1@my-editorial.com, admin2@my-editorial.com"
              withGitPullOptions:
                summary: Example of request body with git pull options
                description: "Module: Deployer"
                value:
                  env: dev
                  site_name: my-editorial
                  replace: false
                  template_name: remote
                  repo_url: ssh://crafter@server/opt/crafter/data/repos/sites/my-editorial/published
                  repo_username: crafter
                  repo_password: crafter
                  repo_branch: live
                  engine_url: http://localhost:8080
                  fast_forward_mode: "FF"
                  merge_strategy: "recursive"
                  content_merge_option: "THEIRS"
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/get/{env}/{site_name}:
    get:
      security: []
      tags:
        - target
      summary: Get a Crafter Deployer target.
      description: "Module: Deployer"
      operationId: getTarget
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Targets'
              example:
                env: dev
                siteName: editorial
                id: editorial-dev
                load_date: 2023-01-26T10:00:01.234-05:00
                status: INIT_COMPLETED
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/get-all:
    get:
      security: []
      tags:
        - target
      summary: Get all Crafter Deployer targets.
      description: "Module: Deployer"
      operationId: getAllTargets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Targets'
              example:
                - load_date: 2023-03-30T13:24:36.042181-04:00
                  env: preview
                  siteName: hi
                  status: INIT_COMPLETED
                  id: hi-preview
                - load_date: 2023-03-31T09:48:48.214383-04:00
                  env: preview
                  siteName: third
                  status: INIT_COMPLETED
                  id: third-preview
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/delete/{env}/{site_name}:
    post:
      security: []
      tags:
        - target
      summary: Delete a Crafter Deployer target.
      description: "Module: Deployer"
      operationId: deleteTarget
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '204':
          description: NO CONTENT
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/delete-if-exists/{env}/{site_name}:
    post:
      security: []
      tags:
        - target
      summary: Delete a Crafter Deployer target if it exists.
      description: "Module: Deployer"
      operationId: deleteTargetIfExists
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '204':
          description: NO CONTENT
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/deploy/{env}/{site_name}:
    post:
      security: []
      tags:
        - target
      summary: Deploy a Crafter Deployer target.
      description: "Module: Deployer"
      operationId: deployTarget
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reprocess_all_files:
                  description: If all files in all the target repos should be reprocessed.
                  type: boolean
                from_commit_id:
                  description: The id of the commit to start processing changes<br><br> <i>Available since version 4.0.0</i>
                  type: string
                deployment_mode:
                  description: "The deployment mode to execute. Possible values: <br> &nbsp;&nbsp;&nbsp;<b>PUBLISH</b>: All processors will run<br> &nbsp;&nbsp;&nbsp;<b>SEARCH_INDEX</b>: Only the indexing processor will run <br><br> <i>Available since version 4.0.0</i>"
                  type: string
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OK
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /api/1/target/deploy-all:
    post:
      security: []
      tags:
        - target
      summary: Deploy all Crafter Deployer targets.
      description: "Module: Deployer"
      operationId: deployAllTargets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reprocess_all_files:
                  description: If all files in all the target repos should be reprocessed.
                  type: boolean
                deployment_mode:
                  description: "The deployment mode to execute. Possible values: <br> &nbsp;&nbsp;&nbsp;<b>PUBLISH</b>: All processors will run<br> &nbsp;&nbsp;&nbsp;<b>SEARCH_INDEX</b>: Only the indexing processor will run <br><br> <i>Available since version 4.0.0</i>"
                  type: string
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/deployments/get-pending/{env}/{site_name}:
    get:
      security: []
      tags:
        - target
      summary: Get the pending deployments for a target.
      description: "Module: Deployer"
      operationId: getPendingDeployments
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
              example:
                [
                  {
                    "mode": "PUBLISH",
                    "status": null,
                    "running": false,
                    "duration": null,
                    "start": null,
                    "end": null,
                    "target": {
                      "env": "preview",
                      "site_name": "ed",
                      "load_date": "2025-03-10T11:44:03.613404-04:00",
                      "status": "INIT_COMPLETED",
                      "id": "ed-preview"
                    },
                    "changeSet": {
                      "created_files": [],
                      "updated_files": [],
                      "deleted_files": []
                    },
                    "processorExecutions": []
                  },
                  {
                    "mode": "PUBLISH",
                    "status": null,
                    "running": false,
                    "duration": null,
                    "start": null,
                    "end": null,
                    "target": {
                      "env": "preview",
                      "site_name": "ed",
                      "load_date": "2025-03-10T11:44:03.613404-04:00",
                      "status": "INIT_COMPLETED",
                      "id": "ed-preview"
                    },
                    "changeSet": {
                      "created_files": [],
                      "updated_files": [],
                      "deleted_files": []
                    },
                    "processorExecutions": []
                  },
                ]
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/deployments/get-current/{env}/{site_name}:
    get:
      security: []
      tags:
        - target
      summary: Get the current deployment for a target.
      description: "Module: Deployer"
      operationId: getCurrentDeployments
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
              example:
                {
                  "mode": "PUBLISH",
                  "status": null,
                  "running": true,
                  "duration": null,
                  "start": "2025-03-11T17:07:00.006221-04:00",
                  "end": null,
                  "target": {
                    "env": "default",
                    "site_name": "ed",
                    "load_date": "2025-03-11T17:00:09.935316-04:00",
                    "status": "INIT_COMPLETED",
                    "id": "ed-default"
                  },
                  "changeSet": {
                    "created_files": [
                      "/site/website/articles/2023/2/10-tips-to-get-in-shape/index.xml",
                      "/site/website/articles/2023/2/top-romantic-valentine-movies/index.xml",
                      "/site/website/articles/2023/3/5-popular-diets-for-women/index.xml",
                      "/site/website/articles/2023/3/top-clubs-in-virginia/index.xml",
                      "/site/website/articles/2023/jan/men-styles-for-winter/index.xml",
                      "/site/website/articles/2023/jan/women-styles-for-winter/index.xml"
                    ],
                    "updated_files": [],
                    "deleted_files": []
                  },
                  "processorExecutions": [
                    {
                      "processor_name": "gitPullProcessor",
                      "start": "2025-03-11T17:07:00.006486-04:00",
                      "end": "2025-03-11T17:07:00.241206-04:00",
                      "status": "SUCCESS",
                      "status_details": "Changes successfully pulled from remote repo /Users/craftercms/crafter-authoring/data/repos/sites/ed/published into local repo /Users/craftercms/crafter-delivery/data/repos/sites/ed (merge result with status Fast-forward)",
                      "running": false
                    },
                    {
                      "processor_name": "gitDiffProcessor",
                      "start": "2025-03-11T17:07:00.241546-04:00",
                      "end": "2025-03-11T17:07:00.254525-04:00",
                      "status": "SUCCESS",
                      "status_details": "Changes detected and resolved successfully",
                      "running": false
                    },
                    {
                      "processor_name": "searchIndexingProcessor",
                      "start": "2025-03-11T17:07:00.255056-04:00",
                      "end": null,
                      "status": null,
                      "status_details": {
                        "successful_updates": [
                          "/site/website/articles/2023/2/10-tips-to-get-in-shape/index.xml",
                          "/site/website/articles/2023/2/top-romantic-valentine-movies/index.xml",
                          "/site/website/articles/2023/3/5-popular-diets-for-women/index.xml"
                        ],
                        "successful_deletes": [],
                        "failed_updates": [],
                        "failed_deletes": [],
                        "successful_updates_and_deletes": 3,
                        "attempted_updates_and_deletes": 3,
                        "failed_updates_and_deletes": 0
                      },
                      "running": true
                    }
                  ]
                }
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/deployments/get-all/{env}/{site_name}:
    get:
      security: []
      tags:
        - target
      summary: Get the current and pending deployments for a target.
      description: "Module: Deployer"
      operationId: getAllDeployments
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
              example:
                [
                  {
                    "mode": "PUBLISH",
                    "status": null,
                    "running": false,
                    "duration": null,
                    "start": null,
                    "end": null,
                    "target": {
                      "env": "preview",
                      "site_name": "ed",
                      "load_date": "2025-03-10T11:44:03.613404-04:00",
                      "status": "INIT_COMPLETED",
                      "id": "ed-preview"
                    },
                    "changeSet": {
                      "created_files": [],
                      "updated_files": [],
                      "deleted_files": []
                    },
                    "processorExecutions": []
                  },
                  {
                    "mode": "PUBLISH",
                    "status": null,
                    "running": false,
                    "duration": null,
                    "start": null,
                    "end": null,
                    "target": {
                      "env": "preview",
                      "site_name": "ed",
                      "load_date": "2025-03-10T11:44:03.613404-04:00",
                      "status": "INIT_COMPLETED",
                      "id": "ed-preview"
                    },
                    "changeSet": {
                      "created_files": [],
                      "updated_files": [],
                      "deleted_files": []
                    },
                    "processorExecutions": []
                  },
                ]
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/unlock/{env}/{site_name}:
    post:
      security: []
      tags:
        - target
      summary: Clear git lock of a Crafter Deployer target.
      description: "Module: Deployer"
      operationId: unlockTarget
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/recreate/{env}/{site_name}:
    post:
      security: []
      tags:
        - target
      summary: Recreate the underlying search index for a Crafter Deployer target.
      description: "Module: Deployer"
      operationId: recreateIndex
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example:
            env: dev
        - name: site_name
          in: path
          description: The target’s project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example:
            site_name: editorial
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/target/duplicate/{env}/{source_site_name}:
    post:
      tags:
        - target
      summary: Duplicate a target
      description: "Module: Deployer"
      operationId: duplicateTarget
      parameters:
        - name: env
          in: path
          description: The target’s environment (e.g. dev).
          required: true
          schema:
            type: string
          example: dev
        - name: source_site_name
          in: path
          description: The source project/site name (e.g. editorial).
          required: true
          schema:
            type: string
          example: editorial
      requestBody:
        description: Duplicate target's request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DuplicateTargetRequest'
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/monitoring/version:
    get:
      security: []
      tags:
        - monitoring
      summary: Get Crafter Deployer's version details.
      description: "Module: Deployer"
      operationId: version
      parameters:
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  packageName:
                    type: string
                  packageVersion:
                    type: string
                  packageBuild:
                    type: string
                  packageBuildDate:
                    type: string
                example:
                  packageName: Crafter Deployer
                  packageVersion: 4.1.0-SNAPSHOT
                  packageBuild: f33f1804c95dd0df4902c9732203841d22022459
                  packageBuildDate: 2023-04-17T21:28:40.642Z
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/monitoring/sysinfo:
    get:
      security: []
      tags:
        - monitoring
      summary: Get Crafter Deployer's system information details.
      description: "Module: Deployer"
      operationId: sysinfo
      parameters:
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  packageName:
                    type: string
                  packageVersion:
                    type: string
                  packageBuild:
                    type: string
                  packageBuildDate:
                    type: string
                  osName:
                    type: string
                  osVersion:
                    type: string
                  osArch:
                    type: string
                  javaVersion:
                    type: string
                  javaVendor:
                    type: string
                  javaVm:
                    type: string
                example:
                  packageName: Crafter Deployer
                  packageVersion: 4.1.0-SNAPSHOT
                  packageBuild: f33f1804c95dd0df4902c9732203841d22022459
                  packageBuildDate: 2023-04-17T21:28:40.642Z
                  osName: Mac OS X
                  osVersion: 13.2.1
                  osArch: x86_64
                  javaVersion: 17
                  javaVendor: Oracle Corporation
                  javaVm: OpenJDK 64-Bit Server VM
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/monitoring/status:
    get:
      security: []
      tags:
        - monitoring
      summary: Get Crafter Deployer's status details.
      description: "Module: Deployer"
      operationId: status
      parameters:
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusInfo:
                    type: object
                    properties:
                      uptime:
                        type: string
                      startup:
                        type: string
                    example:
                      uptime: 49986
                      startup: 2023-04-17T14:16:29.188Z
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/1/monitoring/memory:
    get:
      security: []
      tags:
        - monitoring
      summary: Get Crafter Deployer's memory details.
      description: "Module: Deployer"
      operationId: memory
      parameters:
        - name: token
          in: query
          description: The authorization token
          required: true
          schema:
            type: string
          example: defaultManagementToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MemoryInfo:
                    type: object
                    properties:
                      totalJvmMemory:
                        type: string
                      freeJvmMemory:
                        type: string
                      maxJvmMemory:
                        type: string
                      totalOsMemory:
                        type: string
                      freeOsMemory:
                        type: string
                      totalSwapMemory:
                        type: string
                      freeSwapMemory:
                        type: string
                    example:
                      totalJvmMemory: 154140672
                      freeJvmMemory: 102165520
                      maxJvmMemory: 1073741824
                      totalOsMemory: 34359738368
                      freeOsMemory: 59957248
                      totalSwapMemory: 8589934592
                      freeSwapMemory: 1076363264
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Targets:
      type: object
      properties:
        env:
          type: string
        siteName:
          type: string
        id:
          type: string
        load_date:
          type: string
        status:
          type: string

    Deployment:
      type: object
      properties:
        mode:
          type: string
        status:
          type: string
        running:
          type: boolean
        duration:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        target:
          $ref: '#/components/schemas/Targets'
        changeSet:
          $ref: '#/components/schemas/ChangeSet'
        processorExecutions:
          type: array
          items:
            type: string

    ChangeSet:
      type: object
      properties:
        created_files:
          type: array
          items:
            type: string
        updated_files:
          type: array
          items:
            type: string
        deleted_files:
          type: array
          items:
            type: string

    DuplicateTargetRequest:
      allOf:
        - $ref: '#/components/schemas/CreateTargetRequest'
        - type: object
          properties:
            source:
              allOf:
                - $ref: '#/components/schemas/CreateTargetRequest'

    CreateTargetRequest:
      type: object
      properties:
        env:
          type: string
          description: "The target’s environment (e.g. dev)."
        site_name:
          type: string
          description: "The target’s project/site name (e.g. my-editorial)."
        replace:
          type: boolean
          description: "Replace the existing target."
        template_name:
          type: string
          description: "The template to use for configuration generation. Out-of-the-box remote and local are provided. If not specified, remote will be used."
        disable_deploy_cron:
          type: boolean
          description: "Disables the cron job that runs deployments every certain amount of time."
        repo_url:
          type: string
          description: "Depends on the template. If <i>remote</i> is being used, it specifies the URL of the remote repo to pull from (e.g. ssh://…). If instead the template is <i>local</i>, <i>repo_url</i> is the filesystem path of the local repo (e.g. /opt/..)."
        repo_branch:
          type: string
          description: "Only use with <i>remote</i> template. The branch name of the remote Git repo to pull from. If not specified, the branch will be whatever branch is the current one in the remote repo."
        repo_username:
          type: string
          description: "Only use with <i>remote</i> template. The username of the remote Git repo."
        repo_password:
          type: string
          description: "Only use with <i>remote</i> template. The password of the remote Git repo."
        ssh_private_key_path:
          type: string
          description: "Only use with <i>remote</i> template. The path for the private key used for the remote Git repo."
        ssh_private_key_passphrase:
          type: string
          description: "Only use with <i>remote</i> template. The passphrase for the private key for the remote Git repo (only if the key is passphrase-protected)."
        engine_url:
          type: string
          description: "Base URL of Engine, used to make API calls like clear cache and rebuild context. If not specified, the default is http://localhost:8080."
        notification_addresses:
          type: string
          description: "The email addresses that should receive deployment notifications."
      required:
        - env
        - site_name
        - repo_url


  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Target not found
    Created:
      description: CREATED
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: "OK"

    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Required request parameter 'token' for method parameter type String is not present

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid management token
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Target already exists
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal Server Error
    ServiceUnavailable:
      description: Service unavailable
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not available

    Accepted:
      description: Accepted
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: OK
